"""Serialize an LLMGraph IR back to a Wolfram ``LLMGraph`` you can open in
Mathematica — the reverse of ``tools/wlg2json.wls``.

This closes the round-trip: a natural-language task planned by ``wolfram_agents
do`` is an LLMGraph *structure*, not just LangGraph plumbing. Persisting it as a
Wolfram ``spec = <|name -> "prompt with `Slot`", ...|>; graph = LLMGraph[spec]``
means the artifact is portable *knowledge* — open it in a notebook, inspect the
graph, and run it on a real kernel — exactly the framework's value point.

Faithfulness: the NL planner only ever emits **string-prompt LLM nodes** (see
``planner.validate_ir``), which is precisely the lossless-migration subset — the
backtick slots carry over verbatim and ``LLMGraph`` re-infers ``Input`` and the
output (sink) nodes from them. Dict LLM nodes that pin an explicit ``input`` are
emitted in the association node form ``<|"Prompt" -> ..., "Input" -> {...}|>``.
"""

from __future__ import annotations

import json
from typing import Any


def _wl_string(s: str) -> str:
    """Render a Python string as a Wolfram string literal.

    Backticks (slots) are preserved verbatim; only ``\\`` and ``"`` are escaped
    and newlines are written as ``\\n`` so the literal stays on one line.
    """
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\r\n", "\n").replace("\n", "\\n")
    return f'"{out}"'


def _node_prompt(spec: Any) -> str | None:
    """Extract the prompt string from a string node or an LLM dict node."""
    if isinstance(spec, str):
        return spec
    if isinstance(spec, dict):
        return spec.get("prompt") or spec.get("llm") or spec.get("listable_llm")
    return None


def _render_node(spec: Any) -> str:
    """One node's right-hand side in the ``spec`` association."""
    prompt = _node_prompt(spec)
    if prompt is None:
        raise ValueError(
            "only string-prompt LLM nodes can be exported to Wolfram; "
            f"got a non-LLM node: {spec!r}"
        )
    # A dict node that pins explicit Input (or is listable) needs the assoc form;
    # a bare string lets LLMGraph infer Input from the backtick slots.
    if isinstance(spec, dict) and (spec.get("input") or spec.get("listable_llm")):
        parts = [f'"Prompt" -> {_wl_string(prompt)}']
        if spec.get("input"):
            inputs = ", ".join(_wl_string(str(x)) for x in spec["input"])
            parts.append(f'"Input" -> {{{inputs}}}')
        body = ", ".join(parts)
        tail = "  (* listable: re-check Wolfram listability *)" if spec.get("listable_llm") else ""
        return f"<|{body}|>{tail}"
    return _wl_string(prompt)


def to_wolfram(ir: dict, *, task: str | None = None) -> str:
    """Render an LLMGraph IR as a runnable Wolfram ``.wls`` script.

    The result mirrors ``examples/wolfram/renga_native.wls``: it defines ``spec``
    (the association you pass to ``LLMGraph``) and builds ``graph`` lazily (no LLM
    key needed just to inspect the structure).
    """
    nodes = ir.get("nodes")
    if not isinstance(nodes, dict) or not nodes:
        raise ValueError("IR must have a non-empty 'nodes' map")

    lines = ["#!/usr/bin/env wolframscript",
             "(* ============================================================"]
    if task:
        lines.append(f"   Generated by `wolfram_agents do` from the task:")
        lines.append(f"     {task}")
    lines += [
        "   `spec` is exactly the association you pass to LLMGraph. Backtick",
        "   slots carry the dependencies; LLMGraph infers Input and the output",
        "   (sink) nodes. Open in Mathematica, inspect, or run on a kernel.",
        "   ============================================================ *)",
        "",
        "spec = <|",
    ]
    items = list(nodes.items())
    for i, (name, spec) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lines.append(f"  {_wl_string(name)} -> {_render_node(spec)}{comma}")
    lines.append("|>;")
    lines.append("")
    lines.append("graph = LLMGraph[spec];")
    outputs = ir.get("output")
    if outputs:
        names = ", ".join(str(o) for o in outputs)
        lines.append(f"(* runtime-declared output nodes: {names} *)")
    return "\n".join(lines) + "\n"


def save_graph(ir: dict, base_path: str, *, task: str | None = None) -> dict[str, str]:
    """Write the IR as both ``<base>.json`` (runtime) and ``<base>.wls`` (Wolfram).

    Returns a ``{"json": path, "wls": path}`` map of what was written. Parent
    directories are created as needed.
    """
    import os

    base = base_path[:-5] if base_path.endswith((".json", ".wls")) else base_path
    parent = os.path.dirname(base)
    if parent:
        os.makedirs(parent, exist_ok=True)
    json_path, wls_path = base + ".json", base + ".wls"
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(ir, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    with open(wls_path, "w", encoding="utf-8") as fh:
        fh.write(to_wolfram(ir, task=task))
    return {"json": json_path, "wls": wls_path}


def slugify(task: str, *, max_len: int = 40) -> str:
    """A filesystem-friendly basename derived from a task string."""
    import re

    s = re.sub(r"[^a-zA-Z0-9]+", "-", task.strip().lower()).strip("-")
    return (s[:max_len].rstrip("-") or "graph")
